# Версия Node.js
FROM node:24.11.0 as build

# Рабочая дирректория внутри контейнера Frontend-части продукта Docker Compose
WORKDIR /prod_invest-helper_workspace

COPY ./package*.json ./

RUN npm install --verbose

COPY . .

RUN npm run build

FROM nginx:latest as running

COPY --from=build /prod_invest-helper_workspace/dist /usr/share/nginx/html

COPY --from=build /prod_invest-helper_workspace/src/nginx-conf/default.conf /etc/nginx/conf.d/default.conf

ARG BUILD_TS
ARG BUILD_ID

# fallback: если build args не передали — сгенерируем и положим файл прямо в корень nginx-раздачи
RUN if [ -z "$BUILD_TS" ]; then BUILD_TS=$(date +%s%3N); fi && \
    if [ -z "$BUILD_ID" ]; then BUILD_ID=$(node -e "console.log(require('crypto').randomUUID())"); fi && \
    printf '{ "version": "%s_%s" }' "$BUILD_TS" "$BUILD_ID" > /usr/share/nginx/html/version.json


EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]