# Версия Node.js
FROM node:24.11.0

# Рабочая дирректория внутри контейнера Frontend-части продукта Docker Compose
WORKDIR /dev_invest-helper_workspace

ARG FRONTEND_PORT
ENV FRONTEND_PORT=${FRONTEND_PORT}

# Копируем все файлы у которых наименование начинается на "package" и заканчивается типом файла ".json"
COPY ./package*.json ./

# Устанавливаем NPM зависимости для работы Frontend-части продукта
RUN npm install --verbose

# Копируем все остальные файлы
COPY . .

# Объявляем порт 4200 доступным для открытия внутри контейнера Frontend-части продукта Docker Compose
EXPOSE 4200

# Запускаем Frontend-часть продукта внутри контейнера Docker Compose в режиме разработки и слежки за изменением файлов с кодом
CMD ["sh", "-c", "npx vite --host=0.0.0.0 --port=${FRONTEND_PORT}"]