# Версия Node.js
FROM node:24.11.0 as build

# Рабочая дирректория внутри контейнера Frontend-части продукта Docker Compose
WORKDIR /prod_invest-helper_workspace

COPY ./package*.json ./

RUN npm install --verbose

COPY . .

RUN npm run build

FROM nginx:latest as running

COPY --from=build /prod_invest-helper_workspace/dist /usr/share/nginx/html

COPY --from=build /prod_invest-helper_workspace/src/nginx-conf/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]