# Сервисы поднимаемые в Docker Compose
services:
  # Сервис traefik reverse proxy manager
  prod_traefik_reverse-proxy:
    image: traefik:v3.5
    container_name: prod_traefik_reverse-proxy
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--log.level=DEBUG'
      - '--entrypoints.web.address=:80'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.network=invest-helper_proxynet'
    networks:
      - invest-helper_proxynet
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Сервис frontend приложения
  prod_invest-helper_react-frontend:
    container_name: prod_invest-helper_react-frontend
    build:
      context: ./../../
      dockerfile: ./docker/dockerfiles/react-frontend/Dockerfile.production
    restart: unless-stopped
    environment:
      - PROJECT_STATUS=${DOCKER_MODE}
    expose:
      - 80
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.invest_frontend.rule=Host(`vdska.xn--h1ahceki4e.xn--p1ai`)'
      # - 'traefik.http.routers.invest_frontend.entrypoints=web'
      # - 'traefik.http.services.invest_frontend.loadbalancer.server.port=80'
    networks:
      - invest-helper_prod-net
      - invest-helper_proxynet
    # depends_on:

networks:
  invest-helper_prod-net:
    name: invest-helper_prod-net
    external: true

  invest-helper_proxynet:
    name: invest-helper_proxynet
    external: true
