# Сервисы поднимаемые в Docker Compose
services:
  # Сервис traefik reverse proxy manager
  prod_traefik_reverse-proxy:
    image: traefik:v3.5
    container_name: prod_traefik_reverse-proxy
    command:
      - '--api.insecure=false'
      - '--api.dashboard=true'
      - '--providers.docker=true'
      - '--log.level=DEBUG'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.network=invest-helper_proxynet'
      #Entrypoints:
      - '--entrypoints.web_http.address=:80'
      - '--entrypoints.web_https.address=:443'
      - '--entrypoints.web_http.http.redirections.entrypoint.to=web_https'
      - '--entrypoints.web_http.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.web_http.http.redirections.entrypoint.permanent=true'
      #SSL Let's encrypt:
      - '--entrypoints.web_https.http.tls.certResolver=le'
      - '--certificatesresolvers.le.acme.tlschallenge=true'
      - '--certificatesresolvers.le.acme.email=elmir_kuba@vk.com'
      - '--certificatesresolvers.le.acme.storage=/../../letsencrypt/acme.json'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dashboard.rule=Host(`traefik.vdska.xn--h1ahceki4e.xn--p1ai`)' # echo $(htpasswd -nb admin admin) | sed -e s/\\$/\\$\\$/g
      - 'traefik.http.routers.dashboard.entrypoints=web_https'
      - 'traefik.http.routers.dashboard.service=api@internal'
      - 'traefik.http.routers.dashboard.middlewares=dashboard-auth'
      - 'traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$apr1$$5eFpFlpL$$0E3Xa4qBkIws2Q/xgIIFs/'
    networks:
      - invest-helper_proxynet
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./../../letsencrypt:/letsencrypt

  # Сервис frontend приложения
  prod_invest-helper_react-frontend:
    container_name: prod_invest-helper_react-frontend
    build:
      context: ./../../
      dockerfile: ./docker/dockerfiles/react-frontend/Dockerfile.production
    restart: unless-stopped
    environment:
      - PROJECT_STATUS=${DOCKER_MODE}
    expose:
      - 80
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.invest_frontend.rule=Host(`${FRONTEND_PUBLIC_URL}`)'
    networks:
      - invest-helper_prod-net
      - invest-helper_proxynet

networks:
  invest-helper_prod-net:
    name: invest-helper_prod-net
    external: true

  invest-helper_proxynet:
    name: invest-helper_proxynet
    external: true
